name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # SWA will use Oryx to run npm install + npm run build for Vite
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUSHROOM_0F518751E }}
          action: upload
          app_location: "/"        # your app root
          output_location: "dist"  # ✅ Vite output folder
          # api_location: ""       # empty because your Functions app is separate

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v2
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUSHROOM_0F518751E }}
