name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: If you want to build explicitly (recommended for Vite)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
        env:
          # if you prefer passing env at build time (alternative to SWA Config)
          # VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          # otherwise set VITE_API_BASE in SWA → Configuration
          CI: true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUSHROOM_0F518751E }}
          action: upload
          app_location: "/"          # root of your Vite app
          output_location: "dist"    # ✅ Vite outputs to dist
          # api_location: ""         # leave empty; your Functions are separate
          # skip_app_build: true     # uncomment if you want SWA to deploy prebuilt artifacts
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v2
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_MUSHROOM_0F518751E }}
